### ISSUE TITLE
iOS run error

### ISSUE THREAD

**Issue by 601367322** [OpenFlutter/flutter_image_compress#1]
/Users/bingbing/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.1.2/ios/Classes/CompressFileHandler.h:9:27: Expected a type
/Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:9: While building module 'flutter_image_compress' imported from /Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:
/Users/bingbing/Documents/project/assistant-app/ios/<module-includes>:1:9: In file included from <module-includes>:1:
/Users/bingbing/Documents/project/assistant-app/ios/Pods/Target Support Files/flutter_image_compress/flutter_image_compress-umbrella.h:13:9: In file included from /Users/bingbing/Library/Developer/Xcode/DerivedData/Runner-fvjzjegktdfhfmggngiyngnhzjvp/Build/Products/Debug-iphonesimulator/flutter_image_compress/flutter_image_compress.framework/Headers/flutter_image_compress-umbrella.h:13:
/Users/bingbing/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.1.2/ios/Classes/CompressFileHandler.h:11:35: Expected a type
/Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:9: While building module 'flutter_image_compress' imported from /Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:
/Users/bingbing/Documents/project/assistant-app/ios/<module-includes>:1:9: In file included from <module-includes>:1:
/Users/bingbing/Documents/project/assistant-app/ios/Pods/Target Support Files/flutter_image_compress/flutter_image_compress-umbrella.h:13:9: In file included from /Users/bingbing/Library/Developer/Xcode/DerivedData/Runner-fvjzjegktdfhfmggngiyngnhzjvp/Build/Products/Debug-iphonesimulator/flutter_image_compress/flutter_image_compress.framework/Headers/flutter_image_compress-umbrella.h:13:
/Users/bingbing/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.1.2/ios/Classes/CompressListHandler.h:12:27: Expected a type
/Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:9: While building module 'flutter_image_compress' imported from /Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:
/Users/bingbing/Documents/project/assistant-app/ios/<module-includes>:1:9: In file included from <module-includes>:1:
/Users/bingbing/Documents/project/assistant-app/ios/Pods/Target Support Files/flutter_image_compress/flutter_image_compress-umbrella.h:15:9: In file included from /Users/bingbing/Library/Developer/Xcode/DerivedData/Runner-fvjzjegktdfhfmggngiyngnhzjvp/Build/Products/Debug-iphonesimulator/flutter_image_compress/flutter_image_compress.framework/Headers/flutter_image_compress-umbrella.h:15:
/Users/bingbing/Documents/project/assistant-app/ios/Runner/GeneratedPluginRegistrant.m:8:9: Could not build module 'flutter_image_compress'

**Comment by 601367322** [comment]
add 
`#import <Flutter/Flutter.h>`
to
CompressFileHandler.h

**Comment by CaiJingLong** [comment]
@601367322 thx for issue
I didn't met the problems, and I also used `pub` dependency.
But seem you are right.

fix in #2
