### ISSUE TITLE
webp and jpg same size

### ISSUE THREAD

**Issue by minikupa** [OpenFlutter/flutter_image_compress#109]
String path =
        (await getApplicationDocumentsDirectory()).path + "/$uuid.webp";
    var result = await FlutterImageCompress.compressAndGetFile(
      file.absolute.path, path,
      format: CompressFormat.webp,
      quality: 70,
    );

    String path2 =
        (await getApplicationDocumentsDirectory()).path + "/$uuid.jpeg";
    var result2 = await FlutterImageCompress.compressAndGetFile(
      file.absolute.path, path2,
      format: CompressFormat.jpeg,
      quality: 70,
    );

    print(result.lengthSync());
    print(result2.lengthSync());

in android
Why are result1 and result2 the same size?

**Comment by CaiJingLong** [comment]
Thanks for your #110 to fix the error.
When I resolve #108 error, I will push new version.

**Comment by minikupa** [comment]
Okay, Thanks!
