### ISSUE TITLE
jpg to webp increases the size considerably

### ISSUE THREAD

**Issue by jpainam** [OpenFlutter/flutter_image_compress#119]
Hi, i want to reduce the size of my images by converting to webp. but it increases the size considerably. For example, i have an image of size `88.97KB jpg` and get `224 KB webp`. Here the code. Am I missing something
```dart
 var result = await FlutterImageCompress.compressWithFile(image.path,
            quality: 95,
            format: CompressFormat.webp,
            minHeight: 600);
```
Thank you

**Comment by jpainam** [comment]
Using `quality=70` reduces the size to `75KB webp`. But the image is not resized to `x600`

**Comment by KristianBalaj** [comment]
The problem is that the `jpg` has 24bit depth and the `webp` as a result from this plugin has 32bit (alpha channel added).

Sadly, there is no option to make the `webp` image 24bit with this plugin.

**Comment by jpainam** [comment]
thanks, i see
