### ISSUE TITLE
only release build failed, how to solve it

### ISSUE THREAD

**Issue by xhp281** [OpenFlutter/flutter_image_compress#120]
FAILURE: Build failed with an exception.

* Where:
Build file '~/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-0.6.5/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'flutter_image_compress'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin flutter_image_compress could not be built due to the issue above.

**Comment by Pareshoct7** [comment]
How did you solved this issue?

**Comment by zmGitHub** [comment]
+1

**Comment by CaiJingLong** [comment]
If error message is :`Plugin with id 'com.android.library' not found.`
The `com.android.library` need next config:

If your android/build.gradle(no android/app/build.gradle) add next code:

```groovy
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google() // Add the line
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0' // Add the line
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

If the gradle error log is other, the reason may be inconsistent, please open a new issue to report the problem
