### ISSUE TITLE
A problem occurred evaluating root project 'flutter_image_compress'. > Plugin with id 'com.android.library' not found.

### ISSUE THREAD

**Issue by vitulgoyani** [OpenFlutter/flutter_image_compress#125]
A problem occurred evaluating root project 'flutter_image_compress'.
> Plugin with id 'com.android.library' not found.

**Comment by zzlhr** [comment]
see this issues. https://github.com/OpenFlutter/flutter_image_compress/issues/92

**Comment by gotirahul96** [comment]
Got the same issue.

**Comment by YHX520** [comment]
Got the same issue.

**Comment by AlexV525** [comment]
Please submit new issues if it persists.
