### ISSUE TITLE
[question] Why validating the filename and format?

### ISSUE THREAD

**Issue by hugocbpassos** [OpenFlutter/flutter_image_compress#135]
Commit f355d198eea1c3e56d62dd21534501d3fa44008d brought me a breaking change: [`Validator.checkFileNameAndFormat()`](https://github.com/OpenFlutter/flutter_image_compress/blob/master/lib/src/validator.dart#L12).

I took a look at the native code and seems like both Android and iOS implementations decode the image format-agnostic, therefore there should be no problem if I decide to compress a PNG image as a JPEG. I'm actually doing this and had no problems until now.

Taking that into account, I wonder why did you do such change. I see two possibilities:

1. **I'm wrong.** In this library, you cannot safely decode a PNG image and encode it as JPEG.
2.  **Semantic matters.** You are preventing the user from accidentally encoding the image as JPEG and forgetting to change its filename to ".png".

I'd like to know what exactly do you have in mind, since the way I work around my broken code may be very different depending on your answer.

Either way, you should realize that this is a breaking change and must be introduced as a minor-version update, not as a patch update: instead of "0.6.4", "0.7.0" should have been released.

@CaiJingLong  :)

**Comment by CaiJingLong** [comment]
Hi, I update an new version.

You can add next code to ignore extension name checks of validator.
```dart
FlutterImageCompress.validator.ignoreCheckExtName = true;
```

**Comment by hugocbpassos** [comment]
@CaiJingLong Thanks for the update, but for me it's more important to know the actual reason why you implemented such validation. Can you please clarify it?
