### ISSUE TITLE
Package preventing upgrading Gradle version

### ISSUE THREAD

**Issue by MichaelM97** [OpenFlutter/flutter_image_compress#137]
When attempting to update to Gradle version `3.6.3` I get the following exception

```
A problem occurred configuring project ':flutter_image_compress'.
> Could not resolve all artifacts for configuration ':flutter_image_compress:classpath'.
   > Could not resolve org.apache.httpcomponents:httpcore:4.4.6.
     Required by:
         project :flutter_image_compress > org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50 > de.undercouch:gradle-download-task:3.4.3 > org.apache.httpcomponents:httpclient:4.5.3
      > Could not resolve org.apache.httpcomponents:httpcore:4.4.6.
         > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.pom
            > Could not resolve org.apache.httpcomponents:httpcomponents-core:4.4.6.
               > Skipped due to earlier error
> Could not get unknown property 'android' for project ':flutter_image_compress' of type org.gradle.api.Project.
```

To recreate this, open `android/build.gradle` and update the gradle classpath as so
```gradle
classpath 'com.android.tools.build:gradle:3.6.3'
```

**Comment by CaiJingLong** [comment]
yes upgrade your gradle classpath version to 3.6.3

**Comment by MichaelM97** [comment]
@CaiJingLong sorry my original post had the wrong classpath highlighted, the exception in the original post occurs **after** updating the gradle classpath to `3.6.3`. Can this be reopened please?

**Comment by CaiJingLong** [comment]
Hi, I think you need provide an example to reproduce it.
I think it better be a git repository.

**Comment by MichaelM97** [comment]
@CaiJingLong Sorry I missed your response, recreating this is rather simple, just add the latestest version of `flutter_image_compress` to any Flutter application, and then update the gradle classpath to `3.6.3`. This will prevent the app from building on Android as a Gradle sync will not be possible.
