### ISSUE TITLE
[question] Why validating the filename and format?

### ISSUE THREAD

**Issue by hugocbpassos** [OpenFlutter/flutter_image_compress#140]
> Commit f355d19 brought me a breaking change: Validator.checkFileNameAndFormat().
> 
> I took a look at the native code and seems like both Android and iOS implementations decode the > image format-agnostic, therefore there should be no problem if I decide to compress a PNG image > as a JPEG. I'm actually doing this and had no problems until now.
> 
> Taking that into account, I wonder why did you do such change. I see two possibilities:
> 
> I'm wrong. In this library, you cannot safely decode a PNG image and encode it as JPEG.
> Semantic matters. You are preventing the user from accidentally encoding the image as JPEG and > forgetting to change its filename to ".png".
> I'd like to know what exactly do you have in mind, since the way I work around my broken code may be very different depending on your answer.
> 
> Either way, you should realize that this is a breaking change and must be introduced as a minor-version update, not as a patch update: instead of "0.6.4", "0.7.0" should have been released.

As per #135.

Despite release 0.6.8 allows not validating filename and format, #135 was all about the reason behind validating. Since I did not get an answer, I'm opening this issue again.

**Comment by hugocbpassos** [comment]
I'm closing this due to repo owner's lack of interest.

**Comment by SoftWyer** [comment]
In these situations it's sometimes better to fork the repo and make it better. If other people have the same issue they can use your fork.

Dart/Flutter is great at being able to use code from GitHub directly and not just code published on pubdev.

**Comment by hugocbpassos** [comment]
@SoftWyer As you can see in the title tag, this issue is just a question, and so is #135. Suggesting/requesting a change is not my intention at all, I'm just trying to get a better understanding on why some decisions were taken. I actually made myself clear about that in several situations:

> ***[question]*** Why validating the filename and format?

> ***I'd like to know what exactly do you have in mind***, since the way I work around my broken code may be very different depending on your answer.

> Thanks for the update, but for me ***it's more important to know the actual reason why you implemented such validation***. Can you please clarify it?

The fact that the owner closed #135 by creating a feature, instead of simply answering my question, made me even more confused.
