### ISSUE TITLE
Error installing libwebp.  exmple Demo run ios 

### ISSUE THREAD

**Issue by liuhongen77** [OpenFlutter/flutter_image_compress#147]
Downloading dependencies
Installing Flutter (1.0.0)
Installing Mantle (2.1.1)
Installing SDWebImage (5.8.4)
Installing SDWebImageWebPCoder (0.6.1)
Installing flutter_image_compress (0.0.1)
Installing libwebp (1.1.0)

[!] Error installing libwebp
[!] /usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/n3/bp2rrg5x7mbdfgzdj3g0bg6w0000gn/T/d20200722-87457-sstn74 --template= --single-branch --depth 1 --branch v1.1.0

Cloning into '/var/folders/n3/bp2rrg5x7mbdfgzdj3g0bg6w0000gn/T/d20200722-87457-sstn74'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': Failed to connect to chromium.googlesource.com port 443: Operation timed out

**Comment by CaiJingLong** [comment]
Hi, I think you can see the issue of pinned. 

#123
