### ISSUE TITLE
Black border adding after compress

### ISSUE THREAD

**Issue by dinesh-commits** [OpenFlutter/flutter_image_compress#149]
![Screenshot 2020-07-31 at 4 03 27 PM](https://user-images.githubusercontent.com/59553972/89027035-66db2c80-d347-11ea-9d97-fce4d2bdcdde.png)

```
File compressedImage =
                        await FlutterImageCompress.compressAndGetFile(
                      image.absolute.path,
                      paths +
                          '/compressed_' +
                          DateTime.now().millisecondsSinceEpoch.toString() +
                          '.jpg',
                      quality: 80,
                    );
```

After compressing image I'm getting black border in four side.

**Comment by CaiJingLong** [comment]
I guess your src image is png format.

**Comment by dinesh-commits** [comment]
Yes what is the work around for this ?. I renamed to ".jpg" format and tried to use your library. Its working but black border is coming.

**Comment by CaiJingLong** [comment]
When png is converted to jpg, the transparent color will be converted to black.
This is because png color format is argb and jpg is rgb.
0x00000000(transparent) will be converted to 0x000000(black).

So this problem cannot be solved. 

Recommendation: If it contains transparent pixels, it should be stored in png.

**Comment by dinesh-commits** [comment]
Actually I tested in IOS. Its working fine I'm not getting any border. But in android that black border is coming. That is totally strange!

**Comment by dinesh-commits** [comment]
Its fixed, I removed the transparent section. Thanks a lot for your support.
