### ISSUE TITLE
Xcode version 12.0 error

### ISSUE THREAD

**Issue by yenyichau** [OpenFlutter/flutter_image_compress#156]
Before update my Xcode don't have any error. After updated Xcode to version 12.0 it causes this error.

<img width="261" alt="Screenshot 2020-09-18 at 12 06 28 PM" src="https://user-images.githubusercontent.com/59037547/93555034-8554c000-f9a7-11ea-89bc-96571e1511db.png">

<img width="1167" alt="Screenshot 2020-09-18 at 12 06 15 PM" src="https://user-images.githubusercontent.com/59037547/93555130-b92fe580-f9a7-11ea-9c68-bad322e00e74.png">

Any idea how to solve this issue ? Thanks.

**Comment by Jungho-Cheon** [comment]
same error..

**Comment by yenyichau** [comment]
> same error..

If I'm not wrong i solved this error by using flutter clean > restart.

**Comment by Jungho-Cheon** [comment]
> > same error..
> 
> If I'm not wrong i solved this error by using pod update & pod install > flutter clean > restart.

may i ask your flutter channel and version?

**Comment by yenyichau** [comment]
> > > same error..
> > 
> > 
> > If I'm not wrong i solved this error by using pod update & pod install > flutter clean > restart.
> 
> may i ask your flutter channel and version?

Flutter Version : 1.20.4
Channel : Stable

**Comment by Jungho-Cheon** [comment]
> > > > same error..
> > > 
> > > 
> > > If I'm not wrong i solved this error by using pod update & pod install > flutter clean > restart.
> > 
> > 
> > may i ask your flutter channel and version?
> 
> Flutter Version : 1.20.4
> Channel : Stable

it works! thanks 🥳

**Comment by yenyichau** [comment]
> > > > > same error..
> > > > 
> > > > 
> > > > If I'm not wrong i solved this error by using pod update & pod install > flutter clean > restart.
> > > 
> > > 
> > > may i ask your flutter channel and version?
> > 
> > 
> > Flutter Version : 1.20.4
> > Channel : Stable
> 
> it works! thanks 🥳

You're welcome.

**Comment by willladislaw** [comment]
This is not working for me. `pod update & pod install > flutter clean > restart.`
