### ISSUE TITLE
Can not run with xcode  on real iphone

### ISSUE THREAD

**Issue by libinwalan** [OpenFlutter/flutter_image_compress#157]
Hi
I add this to my flutter project, and run with xcode.  but i got the error as follows:
Undefined symbols for architecture arm64:
  "_SDImageCoderEncodeCompressionQuality", referenced from:
      +[CompressHandler compressDataWithImage:quality:format:] in CompressHandler.o
ld: symbol(s) not found for architecture arm64

PS：run with a simulator is ok.
How can i do to deal with it, thanks!~

**Comment by AllNamesRTakn** [comment]
Same issue here, this seems to be related to the IOS 14 update causing an issue with SDWebImage. 

https://github.com/SDWebImage/SDWebImage/issues/3040

Could probably be fixed by using a newer version of the SDWebImage library?

**Comment by uchiha-itachi95** [comment]
Yes same issue here. Did you find a way to solve this?

**Comment by Dinesh41** [comment]
1. Run "pod install" command.
2. Run ios app from xcode for simulator
3. Then run for real device

It worked for me

**Comment by uchiha-itachi95** [comment]
@Dinesh41  yeah it solved the problem. but why?

**Comment by Dinesh41** [comment]
@uchiha-itachi95 That we have to find

**Comment by zenkog** [comment]
@Dinesh41 Followed your instructions but still doesn't work for me.

**Comment by mnorhamizan** [comment]
Happening on my side as well after upgrading to flutter 1.22

**Comment by Antonimo** [comment]
# me 2

**Comment by qk514112** [comment]
in flutter_image_compress.podspec
set newer iOS version (9.0) than (8.0)
$ cd ios
$ pod install

Pod::Spec.new do |s|
  s.name             = 'flutter_image_compress'
  s.version          = '0.0.1'
  s.summary          = 'A new flutter plugin project.'
  s.description      = <<-DESC
A new flutter plugin project.
                       DESC
  s.homepage         = 'http://example.com'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Your Company' => 'email@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'Flutter'
  s.dependency 'Mantle'
  s.ios.deployment_target = '11.0'
  s.dependency 'SDWebImageWebPCoder'
end

![image](https://user-images.githubusercontent.com/2771993/102909144-7bb18b80-44b3-11eb-850e-74d66484c13a.png)

**Comment by luozantu** [comment]
me 2

**Comment by rlee1990** [comment]
Still happening any updates?

**Comment by ciufab** [comment]
> Still happening any updates?

I tried the solutions above without success, in my case I solved by setting the 'deploy target' to a version > 9.0(I choose 12.0,which is my target min sdk).
Found this solution [here:](https://github.com/OpenFlutter/flutter_image_compress/issues/160#issuecomment-761419272) 
thanks to  ItzNotABug!

**Comment by AlexV525** [comment]
Should be fixed by #182 .
