### ISSUE TITLE
Module flutter_image_compress not found iOS

### ISSUE THREAD

**Issue by sondresorbye** [OpenFlutter/flutter_image_compress#173]
I get this error when trying to archive the app in Xcode. It runs fine when I run it using flutter run. Do anyone know how to fix this?

**Comment by sondresorbye0111** [comment]
<img width="1410" alt="Skjermbilde 2021-03-06 kl  00 09 52" src="https://user-images.githubusercontent.com/22012669/110183962-48bf3880-7e10-11eb-94c7-a67e114558fa.png">

**Comment by danielseow-simplify** [comment]
try Clean Build Folder then Build again
![image](https://user-images.githubusercontent.com/57748006/110286251-9231a280-801f-11eb-8ad7-d024d018c368.png)

**Comment by bhanuka96** [comment]
[flutter_native_image](https://pub.dev/packages/flutter_native_image) user this plugin instead

**Comment by sondresorbye** [comment]
I ended up just using the image_picker plugin
