### ISSUE TITLE
A problem occurred evaluating root project 'flutter_image_compress'.

### ISSUE THREAD

**Issue by UjjwaRaijada** [OpenFlutter/flutter_image_compress#174]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/apple/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-1.0.0-nullsafety/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'flutter_image_compress'.
> Plugin with id 'com.android.library' not found.

Exception: The plugin flutter_image_compress could not be built due to the issue above.

**Comment by UjjwaRaijada** [comment]
can anyone help me with this issue? Thanks

**Comment by antonygunawan94** [comment]
same here, have you found the solution?

**Comment by AlexV525** [comment]
Please submit new issues if it persists.
