### ISSUE TITLE
Flutter 2.2 can't build 

### ISSUE THREAD

**Issue by Shakle** [OpenFlutter/flutter_image_compress#180]
<img width="291" alt="Снимок экрана 2021-05-19 в 10 48 52" src="https://user-images.githubusercontent.com/16610897/118775630-ce8b4580-b88f-11eb-8e55-04af04da091f.png">

Error during build on iOS

**Comment by rlee1990** [comment]
I get the same error.

**Comment by VictorUvarov** [comment]
Have you tried deleting `ios/Podfile.lock` and then running `flutter clean && flutter pub get`

**Comment by mikaelim-id** [comment]
> Have you tried deleting `ios/Podfile.lock` and then running `flutter clean && flutter pub get`

tried this but still got the same error.

**Comment by rakesh4577** [comment]
my app is getting crash when I try to hot reload.

**Comment by mehulTank** [comment]
I am getting the same issue

**Comment by omateuscastro** [comment]
The same error here!

**Comment by Shakle** [comment]
It seems like it started working after cleaning everything, don't really remember what exactly.

Maybe I even removed ios folder and then flutter create . it again.

So the problem is on our machines with library syncing.

**Comment by bhanuka96** [comment]
same issue

I deleted `.symlinks` and 'Pods' and `Podfile.lock` and `Podfile`. But no luck.

**Comment by bhanuka96** [comment]
[flutter_native_image](https://pub.dev/packages/flutter_native_image) user this plugin instead

**Comment by AlexV525** [comment]
Should be fixed by #182 .
