### ISSUE TITLE
CompressAndGetFile returning null

### ISSUE THREAD

**Issue by VillzVic** [OpenFlutter/flutter_image_compress#21]
Calling compressAndGetFile method returning null
![screen shot 2018-12-10 at 12 27 52 pm](https://user-images.githubusercontent.com/23703035/49729926-1e08c880-fc77-11e8-8bd2-5ea8ebe671fc.png),

tried editing the code to print out a response.
![screen shot 2018-12-10 at 12 31 48 pm](https://user-images.githubusercontent.com/23703035/49730095-996a7a00-fc77-11e8-939f-12c634079b45.png)

logs
![screen shot 2018-12-10 at 12 35 12 pm](https://user-images.githubusercontent.com/23703035/49730267-1f86c080-fc78-11e8-98e1-3f5029b10f6b.png)

**Comment by CaiJingLong** [comment]
Can you paste more log? 

![image](https://user-images.githubusercontent.com/14145407/49737273-664fd700-fcc7-11e8-8424-a9fdc9ea7753.png)

-----

In addition, the library won't get any permission, so you need to make sure that your app has permission for targetPath. And targetPath's parent is exists.

**Comment by CaiJingLong** [comment]
Close before new submissions occur, and I will reopen this once a new response occurs or enough information is available.

**Comment by richie-south** [comment]
@CaiJingLong I'm also getting this error, only happens when in released mode works great while debugging which makes this harder to track down :/

Platform tested: Android (version 9)

Flutter doctor
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-SE)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)


Using this code inside a function.
result becomes null
```dart
var dir = Directory.systemTemp;
var targetPath = dir.absolute.path + "/temp.jpg";
File result = await FlutterImageCompress.compressAndGetFile(
    image.absolute.path,
    targetPath,
    quality: 50,
    rotate: 90,
    minHeight: 400,
    minWidth: 400
);

```

**Comment by richie-south** [comment]
Hey i solved it 🎉 Apparently there may be a problem with the paths depending on the device being used [stackoverflow](https://stackoverflow.com/questions/50892268/flutter-permission-denied-writing-file). So by using the included path_provider plugin i created a tmp dir like this 

```dart
import 'package:path_provider/path_provider.dart';

var dir = await getTemporaryDirectory();
var targetPath = dir.absolute.path + "/temp.jpg";
```

Instead of using Directory.systemTemp directly.

This should maybe be included in the readme somewhere :)

**Comment by vapour** [comment]
HI, I resolved it by check the exist of the file to grant permission

> 
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

```dart
// 压缩图片
  Future<File> compressImage(File file) async {
    DateTime now = DateTime.now();
    Directory dir = await getApplicationDocumentsDirectory();
    bool isExist = await file.exists();
    if (!isExist) {
      // 压缩前检测文件是否有权限访问。
      // 如果没检测会报错
      // 不检测，默认只有手机相册图片可访问
      await file.create(recursive: true);
    }
    String tmpPath = dir.absolute.path + '/sxy-${now.millisecondsSinceEpoch}.jpg';
    File newFile = await FlutterImageCompress.compressAndGetFile(
      file.absolute.path, tmpPath,
      format: CompressFormat.jpeg,
      quality: 90,
      minWidth: 1920,
      minHeight: 1080
    );
    return newFile;
  }
```

**Comment by SivaramNalliboyana** [comment]
> Hey i solved it 🎉 Apparently there may be a problem with the paths depending on the device being used [stackoverflow](https://stackoverflow.com/questions/50892268/flutter-permission-denied-writing-file). So by using the included path_provider plugin i created a tmp dir like this
> 
> ```dart
> import 'package:path_provider/path_provider.dart';
> 
> var dir = await getTemporaryDirectory();
> var targetPath = dir.absolute.path + "/temp.jpg";
> ```
> 
> Instead of using Directory.systemTemp directly.
> 
> This should maybe be included in the readme somewhere :)

Thank you, works perfect
