### ISSUE TITLE
iOS crashes when multiple images are compressed in a loop

### ISSUE THREAD

**Issue by ROTGP** [OpenFlutter/flutter_image_compress#22]
When calling FlutterImageCompress.compressWithFile() within a 'for loop' multiple times, iOS crashes with:
> Lost connection to device. Exited (sigterm)

A quick hack to solve this is by pausing (example in the code below) a short time just before compressing, but I'd like a more robust solution. I can confirm that this issue does not affect android. Calling the following code below on iOS with a List of 1 single element does not cause a crash. The ideal solution would be a native function `compressWithFiles` that accepts a `List<String> paths` and compresses multiples images in one call.

```
    List<List<int>> result = [];
    for (int i = 0; i < entityAssets.length; i++) {
      File file = await entityAssets[i].file;

      /// uncomment this to avoid crash on iOS
      /// await Future<Null>.delayed(Duration(milliseconds: 300));
      List<int> compressed = await FlutterImageCompress.compressWithFile(
          file.path,
          rotate: 90,
          minHeight: 1000,
          minWidth: 1000,
          quality: 95);

      result.add(compressed);
    }
```

**Comment by CaiJingLong** [comment]
@ROTGP 
Can you give me a number corresponding to the number of pictures, such as 100 or 1000?
And give the width and height of some original pictures?


----
Look at your code, you seem to be using the `photo_manager` library, which itself has a simple API to get thumbnails of any size .
Before I solve this issue problem, you can use the code: `Uint8List thumbDataWithSize = await entity.thumbDataWithSize(width,height);` to get thumbData.

**Comment by CaiJingLong** [comment]
ok, If I can locate the error, I will fix it as soon as possible.

**Comment by CaiJingLong** [comment]
@ROTGP 
I tried to locate the problem and use the following way to get the image compression, no crash happened.

Can you try to create a new project and use the [code](https://gist.github.com/CaiJingLong/6c57cb1ea070be1e2c04a579511a27a8) replace your main.dart and pubspec.yaml.
run `flutter packages get` and run project in *xcode*. If crash happens , paste your crash logs.

Or give me a minimal runnable example, because where I use the same code as you and find no errors.

**Comment by ROTGP** [comment]
@CaiJingLong I tried to replicate the crash using your code and strangely, I wasn't able to either. I abstracted the code in my other project as much as possible until it was pretty much identical to your example, but it still crashes, very strange. I'm closing this for now, if I can manage to find the issue I'll either reopen it, or comment here for future reference. Thanks for your time and good work

**Comment by MCOfficer** [comment]
I believe i had the same same issue just now. In debugging, there was no specific method call or even image that caused the crash, so i have to think it is hitting some form of memory threshold. All you can do about that is make sure you don't keep the original bytes of an image in memory after having compressed it.

**Comment by CaiJingLong** [comment]
@MCOfficer 
Can you provider some code to reproduce it?

**Comment by MCOfficer** [comment]
i'll see what i can do, but essentially it comes down to
- read the bytes of some (3-5) large (~10MB) images from files
- throw them into compressWithList
- for extra risk, don't discard the original image bytes from memory

**Comment by MCOfficer** [comment]
@ROTGP Here's a minimal example. Select a big, wallpaper-size image, preferably several of them, hit multiply a couple times and then start the compression.

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<List<int>> _images = [];
  List<List<int>> _compressed = [];

  void _pickImage() async {
    File file = await ImagePicker.pickImage(source: ImageSource.gallery);
    setState(() => _images.add(file.readAsBytesSync()));
  }

  void _multiply() {
    setState(() => _images.addAll(List.of(_images)));
  }

  void _compress() async {
    for (List<int> image in _images) {
      List<int> compressed = await FlutterImageCompress.compressWithList(image,
          minHeight: 1000, minWidth: 1000);
      setState(() => _compressed.add(compressed));
    }
  }

  void _clear() {
    setState(() {
      _images = [];
      _compressed = [];
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Selected: ${_images.length} Images',
            ),
            RaisedButton(
              onPressed: _pickImage,
              child: Text('Pick Image'),
            ),
            RaisedButton(
              onPressed: _multiply,
              child: Text('Multiply Selected'),
            ),
            Text(
              'Compressed: ${_compressed.length} Images',
            ),
            RaisedButton(
              onPressed: _compress,
              child: Text('Compress'),
            ),
            RaisedButton(
              onPressed: _clear,
              child: Text('Clear'),
            )
          ],
        ),
      ),
    );
  }
}
```

However, I'm not sure if this is *the* crash, or if this code just crudely forces the app to run out of memory.

**Comment by ROTGP** [comment]
@MCOfficer you'd best open a new issue... I haven't been working with Flutter recently.
