### ISSUE TITLE
Awesome Flutter List

### ISSUE THREAD

**Issue by Solido** [OpenFlutter/flutter_image_compress#24]
I'll be glad to add this library in the awesome flutter list
https://github.com/Solido/awesome-flutter
Would you push a Pull Request ?

So more people can discover this useful plugin !
Thx

**Comment by Solido** [comment]
added

**Comment by CaiJingLong** [comment]
You can use this project anywhere as long as it meets the MIT license.

**Comment by Solido** [comment]
I'm not using it, I'm promoting it !
