### ISSUE TITLE
getImageProperties should include image rotation

### ISSUE THREAD

**Issue by aryzhov** [OpenFlutter/flutter_image_compress#25]
My use case is to store an image in portrait mode with a certain aspect ratio and size. I noticed that on Android, the `getImageProperties` does not work as expected for pictures taken in portrait mode. If the image is in portrait mode, I need to crop it in order to get the desired aspect ratio. However, for  images taken with the built-in camera in Portrait mode, `getImageProperties` returns the size as if the image was in landscape mode. In order to process this case correctly, I need to know the rotation of the image.  `ImageProperties` would be the appropriate place to add the `rotation` attribute.

**Comment by CaiJingLong** [comment]
Your method does not appear in the API of this library. Are you sure you are using this library? And the `getImageProperties ` method belongs to this library?

**Comment by aryzhov** [comment]
OMG, sorry, I am using flutter_native_image.

**Comment by CaiJingLong** [comment]
OK, let me close this issue first. 
If you have other questions, please open a new issue.
