### ISSUE TITLE
MissingPluginException(No implementation found for method compressWithFileAndGetFile on channel flutter_image_compress)

### ISSUE THREAD

**Issue by gaojuanjuan** [OpenFlutter/flutter_image_compress#26]

**Comment by flowhorn** [comment]
You need to fully restart the app, therefore a hot reload etc. doesn't work as Gradle has to rebuild the app dependencies.

**Comment by CaiJingLong** [comment]
To use plugins that contain Android / ios, you must restart the application.
1.  stop application
2.  run application

**Comment by gaojuanjuan** [comment]
ok，Thank you
