### ISSUE TITLE
Image take in portrait mode is rotated 90 degrees

### ISSUE THREAD

**Issue by ethael** [OpenFlutter/flutter_image_compress#3]
Hello,

When I take photo in portrait mode a apply "compressWithFile", I end up with compressed image rotated 90 degrees counterclockwise. 

Tested platform: Android

Flutter doctor:
[✓] Flutter (Channel unknown, v0.9.5, on Linux, locale en_US.utf8)
    • Flutter version 0.9.5 at /opt/flutter-sdk
    • Framework revision 020fd590b0 (3 weeks ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[!] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /opt/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /opt/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] Android Studio (version 3.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at /opt/idea
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4505.50

[✓] Connected device (1 available)
    • Nokia 6.1 • android-arm64 • Android 8.1.0 (API 27)

**Comment by CaiJingLong** [comment]
In some Android devices, cameras take pictures with angles of 90/180/270, and the libraries compress the original images you gave me.
Conversely, if you don't compress, rendering your pre-compressed image directly to the flutter view in Image. file / Image. memory will rotate as well.

**Comment by CaiJingLong** [comment]
in android you can use the method to get normal image.
```kotlin
    private fun setPictureDegreeZero(path: String) {
        try {
            val exifInterface = ExifInterface(path)

            exifInterface.setAttribute(ExifInterface.TAG_ORIENTATION, "no")
            exifInterface.saveAttributes()
        } catch (e: IOException) {
            // TODO Auto-generated catch block
            e.printStackTrace()
        }

    }

```

and the library is not use the method

**Comment by ethael** [comment]
I am taking picture using flutter camera plugin. Then I am using this plugin to compress it and save again to file system for later use. When later shown, it is rotated. I just need it to be positioned correctly.

When I am using native camera app and taking picture in portrait mode, picture is shown correctly in the native gallery app. So problem with unexpected rotation is related to one of the flutter plugins, not the device itself.

**Comment by CaiJingLong** [comment]
Yes, I think your camera plugin need give you the degrees or rotate the image file.
You should ensure that you provide the direction of the picture itself.

**Comment by ethael** [comment]
Thanks for the info. Well, this problem in flutter camera plugin is well known and there is currently no full fix available (https://github.com/flutter/flutter/issues/16587)

Doable solution would be to have ability to rotate picture during the compression. I have done some research and looks like it is not that hard to implement on both platforms. AFAIK you are using Bitmap on Android side where bitmap can be rotated using:

```
Matrix matrix = new Matrix();
matrix.postRotate(90);
Bitmap scaledBitmap = Bitmap.createScaledBitmap(bitmapOrg, width, height, true);
Bitmap rotatedBitmap = Bitmap.createBitmap(scaledBitmap, 0, 0, scaledBitmap.getWidth(), scaledBitmap.getHeight(), matrix, true);
```

on the ios side, there are two possibilities with UIImage. physically rotating the image or changing orientation header in the image. both are described with full code example here:
https://stackoverflow.com/questions/1315251/how-to-rotate-a-uiimage-90-degrees

on the flutter side it means only adding new integer "rotation" parameter to all compress* methods

can you implement this functionality? I have no access to apple device and also missing any experience with Objective C.

**Comment by CaiJingLong** [comment]
It's not hard to rotate pictures. The code for Android / IOS is available. I'll add the optional parameters for rotation in the next version.

But in principle libraries should not provide an automatic rotation scheme, because you don't know if the caller needs you to help him rotate automatically.

**Comment by ethael** [comment]
I understand your point. May I ask when you plan to release next version?

**Comment by lance-blo** [comment]
I would also love to see that resolved, AFAIK there are no reliable way to rotate an image in flutter!
There is a bug in the _image_ package preventing clean rotation on all devices (https://github.com/brendan-duncan/image/issues/72)

**Comment by CaiJingLong** [comment]
link #6

**Comment by CaiJingLong** [comment]
update version 0.1.4

**Comment by technekim** [comment]
[](url)
