### ISSUE TITLE
Does not work on Isolate

### ISSUE THREAD

**Issue by fvisticot** [OpenFlutter/flutter_image_compress#30]
Caught error: Exception: error: native function 'Window_sendPlatformMessage' (4 arguments) cannot be found
flutter: =====>#0      Window.sendPlatformMessage (dart:ui/window.dart:811:9)
#1      BinaryMessages._sendPlatformMessage (package:flutter/src/services/platform_messages.dart:39:15)
#2      BinaryMessages.send (package:flutter/src/services/platform_messages.dart:87:12)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:286:49)
<asynchronous suspension>
#4      FlutterImageCompress.compressWithFile (package:flutter_image_compress/flutter_image_compress.dart:58:35)
<asynchronous suspension>

**Comment by CaiJingLong** [comment]
1. Can you post the code you use?
2. Are you sure your original picture exists?

---

If you have any questions, try clone, repo, and then run the example code to try?

**Comment by fvisticot** [comment]
Using compute...

```
upload({List<int> imageBytes, File file, String trialId}) async {
    LatLng location = (_currentLocation != null)
        ? LatLng(_currentLocation.latitude, _currentLocation.longitude)
        : null;
    final message = PhotoMessage(
        trialId: trialId, file: file, bytes: imageBytes, location: location);

    await compute<PhotoMessage, void>(uploadPhoto, message);
  }
```

```
class PhotoMessage {
  final String trialId;
  final List<int> bytes;
  final File file;
  final LatLng location;

  PhotoMessage({this.trialId, this.bytes, this.file, this.location});

  @override
  String toString() {
    return 'PhotoMessage{trialId: $trialId, location: $location, file: $file}, ';
  }
}
```

```
Future<void> uploadPhoto(PhotoMessage message) async {
  print('Message: $message');
  var bytes = await FlutterImageCompress.compressWithFile(
    message.file.absolute.path,
    minWidth: 1024,
    minHeight: 768,
    quality: 60,
  );

  try {
    return Api().uploadPhoto(
        bytes: bytes, trialId: message.trialId, location: message.location);
  } catch (e) {
    print('Erreur');
  }
}
```

**Comment by CaiJingLong** [comment]
Insert some code at the arrow and check the log to see if the picture exists.

```dart
  var path = message.file.absolute.path;
  var file = File(path);
  print("file exists : ${file.existsSync()}");
  print("file length : ${file.lengthSync()}");
```

![image](https://user-images.githubusercontent.com/14145407/53313209-507ba680-38f3-11e9-847e-689d07446ca3.png)

----

If the file exists and the code does not take effect, you can try to use the code:
```dart
  var file = File(path);
  var bytes = await FlutterImageCompress.compressWithList(
    file.readAsBytesSync(), 
    //...
  );
```

**Comment by fvisticot** [comment]
Following the traces. The file is existing.
With some research I found this:

https://stackoverflow.com/questions/54127158/flutter-window-sendplatformmessage-4-arguments-cannot-be-found

Perhaps your plugins only can be used in the main UI thread.
I use it in a "compute"


flutter: file exists : true
flutter: file length : 1892989
flutter: Tibib Caught error: Exception: error: native function 'Window_sendPlatformMessage' (4 arguments) cannot be found
flutter: =====>#0      Window.sendPlatformMessage (dart:ui/window.dart:811:9)
#1      BinaryMessages._sendPlatformMessage (package:flutter/src/services/platform_messages.dart:39:15)
#2      BinaryMessages.send (package:flutter/src/services/platform_messages.dart:87:12)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:286:49)
<asynchronous suspension>
#4      FlutterImageCompress.compressWithList (package:flutter_image_compress/flutter_image_compress.dart:39:35)
<asynchronous suspension>
#5      uploadPhoto (package:tibib/trial/photos/photos_service.dart:62:42)
<asynchronous suspension>
#6      _IsolateConfiguration.apply (package:flutter/src/foundation/isolates.dart:108:16)
#7      _spawn.<anonymous closure> (package:flutter/src/foundation/isolates.dart:115:33)
#8      Timeline.timeSync (dart:developer/timeline.dart:160:22)
#9      _spawn (package:flutter/src/foundation/isolates.dart:113:12)
#10     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:292:17)
#11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by CaiJingLong** [comment]
You mean, is your code running in isolate?

**Comment by CaiJingLong** [comment]
Because platform functionality is used instead of a pure dart implementation, platform code should not be accessible in a separate isolate.

**Comment by robsonfingo** [comment]
See: https://pub.dev/packages/flutter_isolate

**Comment by CaiJingLong** [comment]
Because of the flutter mechanism, it can not be solved.
I'll close the issue, if you still insist that this is a problem, please open it.

**Comment by monsieurtanuki** [comment]
> Because platform functionality is used instead of a pure dart implementation, platform code should not be accessible in a separate isolate.

@CaiJingLong My naive tests showed that the code is compatible with `isolate`/`compute` on Android but not on iOS.
Is it fair to say that:
1. your package is compatible with `isolate`/`compute` on Android
2. your package is NOT compatible with `isolate`/`compute` on iOS
3. so in my code, I can check the platform first and run your code with `isolate`/`compute` on Android but not on iOS
4. is there a chance that at least one method of your package would work with `isolate`/`compute` on iOS?

**Comment by monsieurtanuki** [comment]
From flutter 3.7 it's possible to use this package with isolate, cf. https://medium.com/flutter/introducing-background-isolate-channels-7a299609cad8

**Comment by neparij** [comment]
For anyone who is stuck on the same problem, here is my solution 🚀🚀🚀

### Create a model class for compression requests to run in isolate:
```dart
class CompressionRequest {
  final RootIsolateToken token;
  final SendPort sendPort;
  final String filePath;
  final String targetPath;
  final int minWidth;
  final int minHeight;
  final int quality;

  CompressionRequest(this.token, this.sendPort, this.filePath, this.targetPath, this.minWidth, this.minHeight, this.quality);
}
```

### In your class - create a static method that should be spawned in isolate:
```dart
static void _compressImage(CompressionRequest request) async {
  BackgroundIsolateBinaryMessenger.ensureInitialized(request.token);
  final compressedImage = await FlutterImageCompress.compressAndGetFile(
    request.filePath,
    request.targetPath,
    minWidth: request.minWidth,
    minHeight: request.minHeight,
    quality: request.quality,
    format: CompressFormat.jpeg,
  );

  request.sendPort.send(compressedImage?.path);
}
```

### Create a Future method in your class to spawn an isolate:
```dart
Future<XFile?> compressImageInIsolate(String filePath, String targetPath, int minWidth, int minHeight, int quality) async {
  final RootIsolateToken rootIsolateToken = RootIsolateToken.instance!;
  final receivePort = ReceivePort();
  final sendPort = receivePort.sendPort;
  final compressionRequest = CompressionRequest(rootIsolateToken, sendPort, filePath, targetPath, minWidth, minHeight, quality);

  await Isolate.spawn(_compressImage, compressionRequest);

  final compressedImagePath = await receivePort.first as String?;
  return compressedImagePath != null ? XFile(compressedImagePath) : null;
}
```


### Usage:
```dart
await compressImageInIsolate(
  photo.file.path,
  "${photo.file.path}-compressed.jpg",
  1080,
  1080,
  70,
);
```

**Comment by neparij** [comment]
@CaiJingLong , I've found a solution, you can see it in the message above and change the label `solve: unable to solve` :)
