### ISSUE TITLE
Would you consider doing an image resize?

### ISSUE THREAD

**Issue by psyanite** [OpenFlutter/flutter_image_compress#32]
I found this library extremely slow and memory consuming: https://pub.dartlang.org/packages/image

Was wondering if you would consider adding some resize APIs, my use case is uploading pictures to Firebase, and I need to find the smallest file-size possible. Users could select images of anywhere between 100KB to 5MB, so I would like to do a resize to width: 1080 (like what instagram does)

Thank you.

**Comment by CaiJingLong** [comment]
Compression and encoding of pictures are related to the content of pictures.
The width and height of the picture are the same as the other picture.
The size of another solid-color image will be very small, while the color is rich, the size will also increase.
So it's hard to know the size of the file before compression.

---
Resize has many ways. This library compresses the quality of the image and converts it to JPEG format to achieve the effect. During the compression process, the aspect ratio of the image will remain unchanged.
If you need crop images based on size/offset, other libraries are recommended, such as [flutter_native_image](https://github.com/btastic/flutter_native_image)

**Comment by psyanite** [comment]
Hi, thanks for your quick reply. I see that compression is related to the content the byte data. But if I resize the photo first (for example from 3000 X 3000 to 1000 X 1000) it's going be much smaller after compression is that correct? 

I was wondering if this library would consider adding similar apis for resize independent or during compression?

**Comment by CaiJingLong** [comment]
There are `minWidth` and `minHeight` parameters that can be used to adjust the size. This parameter ensures that the aspect ratio remains unchanged.

But crop are not supported(the rectangle becomes a square).

**Comment by psyanite** [comment]
Yeah but it's a minimum, it doesn't take it resize always.
