### ISSUE TITLE
Optimize memory usage of compressAndGetFile

### ISSUE THREAD

**Issue by kinex** [OpenFlutter/flutter_image_compress#34]
The code in BitmapCompressExt.kt always creates the whole bitmap in memory (`ByteArrayOutputStream`) even if final output is wanted in a file. I think it would be better to pass `FileOutputStream` directly to `Bitmap.compress`, something like this:
```java
val fos = FileOutputStream(outputFilePath)
Bitmap.createScaledBitmap(this, destW, destH, true)
        .rotate(rotate)
        .compress(Bitmap.CompressFormat.JPEG, quality, fos)
fos.close()
```
I believe that would consume much less memory.

**Comment by kinex** [comment]
Thanks for your quick fix! One possible issue, should you close the streams? From what I know not closing streams may lead to memory leaks or allocated files. One option is to use the "use" statement in Kotlin, some related samples: https://stackoverflow.com/questions/35528409/write-a-large-inputstream-to-file-in-kotlin

**Comment by CaiJingLong** [comment]
Forget it, `ByteArrayOutputStream` was used before, and it didn't need close.
