### ISSUE TITLE
Missing function "getImageProperties"

### ISSUE THREAD

**Issue by kinex** [OpenFlutter/flutter_image_compress#37]
In my app I want to scale all large images to some smaller size e.g. 1920x1024. But I don't want to touch images which are already of that size or smaller. This plugin allows specifying only minimum size so it will also stretch small images to larger size which I don't want to happen.

So what I am missing is a lightweight method for getting the current image size. Wouldn't this kind of function be logical part of this plugin? Here is one sample how to get image dimensions in Android: https://stackoverflow.com/questions/11128481/android-get-image-dimensions-without-opening-it

There are some other plugins to get image properties, but none of them what I have found do it "correctly" (they read the whole image in memory which is no-go for my app).

**Comment by CaiJingLong** [comment]
There's an example code in readme that tells you how the plugin works in the smallest size.

https://github.com/OpenFlutter/flutter_image_compress#about-params

When the original picture itself has met the requirements, the size of the picture will not change.
But the quality and angle will still vary depending on the size of the input.

-----

Getting image size is not the function of this plugin.

The plugin is only compress your image . 

The params `minWidth`,`minHeight` is designed to ensure that the aspect ratio of the image remains unchanged.

**Comment by kinex** [comment]
Ok, good to know that small images are not stretched. That improves the situation slightly, but in my use case I still cannot know if an image has already been optimized or not (without knowing its dimensions) due to situations like restoring app data (images) from an earlier backup file etc. I try to find some workaround. Clearly I cannot call `compressAndGetFile` for the same file multiple times as it would decrease the image quality on each call.

**Comment by CaiJingLong** [comment]
Dart provides access to image size, which can be used with simple encapsulation.

```dart
import 'dart:ui' as ui;
import 'dart:async';
import 'dart:typed_data';

Future<Size> getImageForUint8List(Uint8List imageSrc) {
  Completer<Size> completer = Completer();
  ui.decodeImageFromList(imageSrc, (img) {
    completer.complete(Size(img.width.toDouble(), img.height.toDouble()));
    img.dispose();
  });
  return completer.future;
}
```

**Comment by CaiJingLong** [comment]
Or if you need to get the size of the picture, you can use some other libraries to achieve it.

**Comment by kinex** [comment]
Decoding an image file and reading it to memory just to get its dimensions does not make sense, so the above Dart code is not usable.

**Comment by CaiJingLong** [comment]
In the case of a large number of images, you may need to use EXIF plug-ins. @kinex

**Comment by kinex** [comment]
Here is one way to do it:  https://gist.github.com/kinex/b2c11e53473e53f7b207a919358d06ae

**Comment by CaiJingLong** [comment]
Thank your gist code.
But I probably won't add this code to the library because the library's goal is to reduce the file size of the image by reducing its quality and zooming.
Whether the original image needs to be compressed or not should be judged by the caller of the library.

**Comment by kinex** [comment]
I didn't mean you should add it to your library, it would not even make sense since my gist is not platform dependent code. Sample code in gist was mainly a response to your suggestion to use exif plugin, as you see there are better ways to do it. It is ok if you want to limit your library only to compression apis. I will close this ticket.
