### ISSUE TITLE
[Android] path Must not be null

### ISSUE THREAD

**Issue by tudor07** [OpenFlutter/flutter_image_compress#40]
Crashes on Android. iOS works fine.
To get the image I use image_picker and pick the image from gallery. If I pick from camera it works fine, so the issue is only when getting the image from gallery.

```
I/flutter (19871): The following ArgumentError was thrown:
I/flutter (19871): Invalid argument(s) (path): Must not be null
I/flutter (19871): 
I/flutter (19871): When the exception was thrown, this was the stack:
I/flutter (19871): #0      ArgumentError.checkNotNull (dart:core/errors.dart:181:27)
I/flutter (19871): #1      new _File (dart:io/file_impl.dart:210:19)
I/flutter (19871): #2      new File (dart:io/file.dart:255:18)
I/flutter (19871): #3      FlutterImageCompress.compressAndGetFile (package:flutter_image_compress/flutter_image_compress.dart:90:12)
I/flutter (19871): <asynchronous suspension>
```

flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.2.1 at /Users/tudor/dev/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tudor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/tudor/Library/Android/sdk
    • Java binary at: /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/tudor/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • SM G950F • 988a1644544d44384c • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by CaiJingLong** [comment]
As given in the information: Path must not be null.
You have to make sure that the incoming path is not empty in your code.

In `image_picker`, if you exit without selecting a image, the result is null, so if you use `file?.path` to get a path, the path is null. Then passing this value to the native will cause problems.

I will deal with this situation in the code, but you also need to make sure the params is not null.

**Comment by CaiJingLong** [comment]
close by #41

**Comment by tudor07** [comment]
@CaiJingLong Can you please re-open this issue ? Sorry, but I disagree with this behaviour of quickly closing issues based on your personal assumptions.

I don't pass null to this plugin and I don't exit `image_picker` without selecting an image. I send valid data and it fails. I don't know what the exception is because I took a look at the code and there is an `catch(Exception ) {result(null)}` line which doesn't log the exception.

**Comment by CaiJingLong** [comment]
I'm not assuming to close the issue.
I modified it to handle the case where the input parameter is null from the dart layer.

If you still have problems using this library, please paste the log here.
The Android section can use ADB logcat to view native logs.

**Comment by tudor07** [comment]
Thanks. The issue with pasting the logs is that I think the library crashes on native side, but the exception is swallowed here: https://github.com/OpenFlutter/flutter_image_compress/blob/f18bd08f3cfd923f101eb817d82f6d024ef17021/android/src/main/kotlin/com/example/flutterimagecompress/CompressFileHandler.kt#L50

I think if the exception would be logged we would be able to see it.

**Comment by CaiJingLong** [comment]
Then post the log here and I will try to help you solve this problem.

**Comment by tudor07** [comment]
Yes, now I can get the logs. Looks like it crashes because of storage permission.


```
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Camera/20190414_210950.jpg (Permission denied)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.io.FileOutputStream.open0(Native Method)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:308)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at com.example.flutterimagecompress.CompressFileHandler$handleGetFile$1.run(CompressFileHandler.kt:46)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-04-17 16:53:26.500 11826-13419/{my_app}} W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-04-17 16:53:26.511 11826-11948/{my_app}} I/flutter: Another exception was thrown: NoSuchMethodError: The getter 'path' was called on null.
```

**Comment by tudor07** [comment]
It's strange, why does it need storage permission ? For example `flutter_native_image` (another library for compression) works without storage permission.

**Comment by tudor07** [comment]
Looks like this library tries to write to `Camera` folder while the other library writes to `Context.getExternalCacheDir()` which is a directory owned by the app.

**Comment by CaiJingLong** [comment]
No, the `path` and `targetPath` of `flutter_image_compress` is provided by the caller, who should ensure permission for the directory.

https://github.com/OpenFlutter/flutter_image_compress/blob/8d8a49dd38c70122f47e055731a5a06b815f0705/lib/flutter_image_compress.dart#L91-L98

**Comment by tudor07** [comment]
Now I understand. Yes, I think it's a good idea for this to be configurable.
Thanks a lot for the help, you can close this issue.

**Comment by CaiJingLong** [comment]
In fact, I added the same question to Readme long ago.

https://github.com/OpenFlutter/flutter_image_compress#troubleshooting
