### ISSUE TITLE
Calling compressWithList returns null

### ISSUE THREAD

**Issue by itlws** [OpenFlutter/flutter_image_compress#42]
![image](https://user-images.githubusercontent.com/7419461/56783236-51f71b80-681d-11e9-8835-44901275db95.png)
i set the ImageByteFormat to ImageByteFormat.rawRgba，Calling compressWithList returns null;
if i set the ImageByteFormat to ImageByteFormat.png,Calling compressWithList returns the correct result

**Comment by CaiJingLong** [comment]
Perhaps there is a problem with the captured image, or the format conversion is not supported natively.

**Comment by CaiJingLong** [comment]
The problem as explained in Readme in detail. 

I'll close the issue, and if there's still a problem, You can reopen it.
