### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'

### ISSUE THREAD

**Issue by dokinkon** [OpenFlutter/flutter_image_compress#43]
Hi, I cannot build my flutter app with 'flutter_image_compress 0.4.0'.

The error message is 

file:///Users/dokinkon/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.4.0/lib/flutter_image_compress.dart:188:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/dokinkon/Case/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: 'image load failed ',

I guess this issue maybe caused by the change of flutter SDK? Thanks.

Below is my flutter doctor:
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.124, on Mac OS X 10.14.4 18E226, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

**Comment by CaiJingLong** [comment]
Can you provide a minimum repeatable modern code?

**Comment by RafaO** [comment]
I am also facing this issue. Apparently, the flutter team introduced a breaking change and plugins need to adapt. They have an issue where they also posted a list of plugins that need to update. https://github.com/flutter/flutter/issues/31962

**Comment by dokinkon** [comment]
After upgrading to v0.4.0, every thing is ok.

**Comment by Skquark** [comment]
That error is from a breaking change on the Flutter Dev and Master channels with the .reportError function.  The context parameter is no longer a string, so where it says:
context: 'image load failed ',
it is now
context: ErrorDescription('image load failed '),
.... a bunch of packages have been breaking this week because of it.  Should probably update v0.5.0 and leave 0.4.0 since it doesn't effect the Stable channel yet..

**Comment by CaiJingLong** [comment]
@Skquark 
See Readme : https://github.com/OpenFlutter/flutter_image_compress#about-version

This change is not on flutter stable version now.
So use git ref instead of the version on pub.
