### ISSUE TITLE
Crash in flutter v1.5.9

### ISSUE THREAD

**Issue by dingzuhua** [OpenFlutter/flutter_image_compress#44]
file:///Users/dingzuhua/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-0.4.0/lib/flutter_image_compress.dart:188:16: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
     - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/dingzuhua/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
    Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
          context: 'image load failed ',

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.5.9-pre.196, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by dingzuhua** [comment]
I refer to the old version of the flutter SDK, where the context is of type String, and when the flutter SDK is updated, it becomes DiagnosticsNode type

**Comment by jimmykuu** [comment]
in file "lib/flutter_image_compress.dart", line: 188, change it as below:
```
FlutterError.reportError(new FlutterErrorDetails(
  context: DiagnosticsNode.message('image load failed '), // 'image load failed '
  library: 'flutter_image_compress',
  exception: exception,
  stack: stackTrace,
  silent: true,
));
```

**Comment by CaiJingLong** [comment]
@jimmykuu 
Thanks for answer, can you tell me which version of this type of change started?
I'll update it and add an SDK constraint to avoid this error.

**Comment by jimmykuu** [comment]
Flutter (Channel master, v1.5.9-pre.285, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.9-pre.285 at 
    • Framework revision eba005e94e (8 hours before), 2019-05-16 21:57:39 -0400
    • Engine revision b6981a38b9
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 5ffff98440)

flutter_image_compress: ^0.4.0

**Comment by CaiJingLong** [comment]
1.5.9 version was removed by flutter team.
I will update a middle version number to support flutter 1.6.0.
At the same time, version 0.4.x will not add new functionality except for possible bug fixes.
