### ISSUE TITLE
iOS error

### ISSUE THREAD

**Issue by c0h1b4** [OpenFlutter/flutter_image_compress#51]
Hello, I am getting this error when running on iOS:

`...flutter/.pub-cache/git/flutter_image_compress-5a545f7e5409d091cd18f5891a8b07426f390729/lib/flutter_image_compress.dart:205:32: Error: No named parameter with the name 'onError'.
...flutter/.pub-cache/git/flutter_image_compress-5a545f7e5409d091cd18f5891a8b07426f390729/lib/flutter_image_compress.dart:207:27: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.`

My code:

```dart
File processImage({File oldImage}) async {
   final Directory tmpDirectory = await Directory.systemTemp.createTemp();
   File myNewFile = await FlutterImageCompress.compressAndGetFile(
        oldImage.path, tmpDirectory.path,
        quality: 66);
   return myNewFile;
}
```

flutter doctor -v:
```bash
[✓] Flutter (Channel dev, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-BR)
    • Flutter version 1.6.3 at /Users/mauro/development/flutter
    • Framework revision bc7bc94083 (2 days ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mauro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mauro/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mauro/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPhone Mauro • e1216cebac409d83bc8d37bde15f8af53564c933 • ios • iOS 12.3
```

**Comment by paqio** [comment]
Same here

**Comment by deakao** [comment]
Solution:
Edit file flutter_image_compress.dart line 205 - 208
stream.addListener(ImageStreamListener(listener, onError: errorListener));
completer.future.then((ImageInfo info) {
    stream.removeListener(ImageStreamListener(listener));
});

**Comment by CaiJingLong** [comment]
So, this is a breaking change in the master branch.

See dart-lang/pub-dev#2290

The update strategy for this library will follow pub.
If there is a breaking change, wait for the stable version to arrive at the corresponding version to update.

Before that, I will take this as a future goal and wait for the release of the flutter stable version.

**Comment by agetman-gh** [comment]
@CaiJingLong thank you for great lib!

Could you make git ref dependency with Flutter dev channel solution for this bug (just like @deakao proposed above)?

**Comment by CaiJingLong** [comment]
@agetman-gh 
That's a good idea. I'll use a branch to gradually adapt to the new version of flutter.

**Comment by CaiJingLong** [comment]
To solve this problem, I added a branch of follow-flutter-dev, which can be temporarily solved by ref on this branch.

See https://github.com/OpenFlutter/flutter_image_compress#flutter-163

**Comment by CaiJingLong** [comment]
Because of the redesign of the version strategy, I deleted a call to the frequently changing API within flutter, and now the latest version of 0.6.0 can be used directly regardless of the version of flutter sdk.
