### ISSUE TITLE
Another breaking changes with latest Flutter upgrade

### ISSUE THREAD

**Issue by Skquark** [OpenFlutter/flutter_image_compress#53]
On the Dev and Master channels this week, looks like they changed the ImageStream handling of errors and reworked it a bit.  I looked into it a little and see that you need to set up an ImageStreamListener now instead of the onError..
Here are the latest errors we're getting:
```
file:///D:/Program%20Files/Android/flutter/.pub-cache/git/flutter_image_compress-5a545f7e5409d091cd18f5891a8b07426f390729/lib/flutter_image_compress.dart:205:32: Error: No named parameter with the name 'onError'.
  stream.addListener(listener, onError: errorListener);
                               ^^^^^^^
file:///D:/Program%20Files/Android/flutter/.pub-cache/git/flutter_image_compress-5a545f7e5409d091cd18f5891a8b07426f390729/lib/flutter_image_compress.dart:207:27: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///D:/Program%20Files/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').      
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///D:/Program%20Files/Android/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.removeListener(listener);
```
Here's the change discussions that should help in fixing it: [https://github.com/flutter/flutter/issues/32935](https://github.com/flutter/flutter/issues/32935) but wasn't finding many code examples..
I played around with it a little to see if I could figure it out, and got rid of the void listener() and ended up with something like this on line 205:
```
  //stream.addListener(listener, onError: errorListener);
  ImageStreamListener listener = ImageStreamListener((ImageInfo image, bool sync) {
    completer.complete(image);
  }, onError: errorListener);
  stream.addListener(listener);
  completer.future.then((ImageInfo info) {
    stream.removeListener(listener);
  });
```
Not saying this is it, I didn't want to put too much time with it, but would be nice to get it building again, so I wanted to help speed up the upgrade pains if I could...

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_image_compress/issues/51#issuecomment-496330303

**Comment by boeledi** [comment]
Another change to be applied (at the level of the context)
```
void errorListener(dynamic exception, StackTrace stackTrace) {
    completer.complete(null);
    FlutterError.reportError(FlutterErrorDetails(
      context: DiagnosticsNode.message('image load failed '),
      library: 'flutter_image_compress',
      exception: exception,
      stack: stackTrace,
      silent: true,
    ));
  }
```

**Comment by CaiJingLong** [comment]
@boeledi  The change is commited at [ref](https://github.com/OpenFlutter/flutter_image_compress/commit/c3c891d0be54f0892bcb4e9c4608d7ad1498e73c).

Readme: https://github.com/OpenFlutter/flutter_image_compress#flutter-160

After the latest version of pub supports these changes, I will move branch merge to master branch, but before that, use git to import.
```yaml
dependencies:
  flutter_image_compress:
    git:
      url: https://github.com/OpenFlutter/flutter_image_compress.git
      ref: c3c891d0be54f0892bcb4e9c4608d7ad1498e73c
```

**Comment by CaiJingLong** [comment]
Because of the redesign of the version strategy, I deleted a call to the frequently changing API within flutter, and now the latest version of 0.6.0 can be used directly regardless of the version of flutter sdk.
