### ISSUE TITLE
项目集成插件后报错，无法运行

### ISSUE THREAD

**Issue by muyi0728** [OpenFlutter/flutter_image_compress#56]
运行报错信息： Cannot fit requested classes in a single dex file
flutter 版本 ： 1.5.4-hotfix.2

**Comment by CaiJingLong** [comment]
It doesn't look like a problem with this plug-in.

**Comment by muyi0728** [comment]
解决了，我在 build.gradle 的 defaultConfig 配置  multiDexEnabled true  就能正常运行了，我也不确定是不是 flutter_image_compress 插件导致的，但我之前移除这个插件后是可以正常运行的，加入后就会报 Cannot fit requested classes in a single dex file

**Comment by CaiJingLong** [comment]
MultDex is used to solve the problem of 63335 of methods. So, if your total number of methods more that number, you will always get is error.

But anyway, it's good to solve it.
