### ISSUE TITLE
NoSuchMethodError: The getter 'path' was called on null.

### ISSUE THREAD

**Issue by damo2** [OpenFlutter/flutter_image_compress#57]
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: pathetter 'path' was called on null.

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_image_compress#compressing-returns-null

**Comment by shenwilly** [comment]
Experienced this, permission is already granted and path is available via `path_provider`

this is the log via `FlutterImageCompress.showNativeLog = true;`
no errors whatsoever 
```
I/System.out( 7930): src width = 720.0
I/System.out( 7930): src height = 592.0
I/System.out( 7930): width scale = 0.375
I/System.out( 7930): height scale = 0.54814816
I/System.out( 7930): scale = 1.0
I/System.out( 7930): dst width = 720.0
I/System.out( 7930): dst height = 592.0
```
