### ISSUE TITLE
Transparent color is colored black on PNGs

### ISSUE THREAD

**Issue by friebetill** [OpenFlutter/flutter_image_compress#58]
When I compress a PNG image, the transparent area is replaced with black. So many of the PNG images are unusable, is it perhaps possible to leave it transparent or at least color it white?

I attached a sample image, compressed and not compressed.
![before_compression](https://user-images.githubusercontent.com/10923085/60041208-13fe6280-96bb-11e9-83ed-03544080b12c.png)
![after_compression](https://user-images.githubusercontent.com/10923085/60041207-13fe6280-96bb-11e9-968c-97b4f773ecda.png)

**Comment by CaiJingLong** [comment]
Now target of compress is a jpeg.
I think need a option to compress to png format.

**Comment by CaiJingLong** [comment]
Because of the software update strategy, this function will only be updated on the dev branch.

**Comment by CaiJingLong** [comment]
Please update version to 0.6.0.
The problem will be fixed.

**Comment by mminhlequang** [comment]
seem this issue back again if compress png on web
