### ISSUE TITLE
i get an exception 

### ISSUE THREAD

**Issue by ektelat** [OpenFlutter/flutter_image_compress#60]
[ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty

 Future<List<int>> testCompressFile(File file) async {
    var result = await FlutterImageCompress.compressWithFile(file.absolute.path,
        minWidth: 700, quality: 80, rotate: 90);
    print(file.lengthSync());
    print(result.length);
    return result;
  }

console

I/flutter (26332): 3465236
I/flutter (26332): 0
E/flutter (26332): [ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty
I/flutter (26332): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (26332): The following _Exception was thrown resolving an image codec:
I/flutter (26332): Exception: operation failed
I/flutter (26332): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by CaiJingLong** [comment]
It seems that the picture coding is incorrect.

There may be several reasons:
1. Document encoding is not supported, png/jpeg is supported, other formats are not guaranteed.
2. The path is incorrect for the file where the incoming image is located, or the file does not exist.

**Comment by CaiJingLong** [comment]
Can you post a example to help me locate the problem?
Gist or dart file or repository.

**Comment by CaiJingLong** [comment]
I will close this.
If there is a new change, please re-open it.
