### ISSUE TITLE
非常抱歉，提了个无关该项目的issues

### ISSUE THREAD

**Issue by juggist** [OpenFlutter/flutter_image_compress#61]
你好，首先非常抱歉在该项目下提一个无关的issues。
     
 我在发布flutter插件的时候遇到了一些问题，然后参照了你的这篇文章
"https://blog.csdn.net/qq_28478281/article/details/87283345。"
确保的curl google.com返回信息，使用flutter packages pub publish --dry-run 返回的第一行提示为"Publishing flutter_encrypt_lib 1.0.0 to https://pub.dartlang.org:"。

 然后使用"flutter packages pub publish --server=https://pub.dartlang.org"，输入"y"，返回了一个url认证，点击链接后，控制台一直显示
"
Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 55083
pub finished with exit code 69
"
    能获取一下你的帮助嘛？多谢了。
    以下是"flutter doctor"
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (1 available)
    再次感谢你查看我的issues

**Comment by CaiJingLong** [comment]
link to : https://github.com/CaiJingLong/kikt-blog-comment/issues/10
