### ISSUE TITLE
autoCorrectionAngle switches image width and height

### ISSUE THREAD

**Issue by gtrochimiuk** [OpenFlutter/flutter_image_compress#62]
I am using this library to compress an in-memory image to a certain width:
```
final compressedBytes = await FlutterImageCompress.compressWithList(
      bytes,
      minWidth: targetWidth,
      minHeight: 0,
    );
```
On some Android devices (i.e. Samsung Galaxy S6) I have a problem with resulting image size - height is equal to `targetWidth` and width is scaled to keep the aspect ratio.

I think that the problem is caused by `autoCorrectionAngle` - it rotates the image to keep orientation (which is what I want), but it does not adjust width and height values to the rotation.

Would it be possible to change the behaviour of auto correcting orientation to also switch width with height if needed, so that resulting image width is equal to targetWidth I specify? If not - is there a way for me to know which image will be rotated by `autoCorrectionAngle = true` so that I can specify a `targetHeight` instead of `targetWidth` to achieve the same result?

**Comment by CaiJingLong** [comment]
There is no way to know the current version.
Because the direction information comes from `ExifInterface`, an Android native interface, it is not exposed on the dart side.

**Comment by CaiJingLong** [comment]
So I should modify the order of minWidth and autoCorrectionAngle so that this property takes effect before minWidth, not after.
