### ISSUE TITLE
WARNING: API 'variant.getPackageLibrary()' is obsolete

### ISSUE THREAD

**Issue by GerlanStanley** [OpenFlutter/flutter_image_compress#75]
Hello, I am receiving this warning, is there anything I should do not to receive it?

WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: flutter_image_compress

**Comment by CaiJingLong** [comment]
This problem see seem kotlin's problem.
---
Now, you can ignore the warning.
