### ISSUE TITLE
压缩10M左右的图片内存不足直接闪退

### ISSUE THREAD

**Issue by liuyun1014** [OpenFlutter/flutter_image_compress#76]

**Comment by CaiJingLong** [comment]
Android or ios?

Please provide a example and provide a 10M+ picture.

I try to fix it.

**Comment by liuyun1014** [comment]
yes,The same question

**Comment by liuyun1014** [comment]
Where do I send the pictures?

**Comment by CaiJingLong** [comment]
Can you provide a 10M+ picture as an attachment?

**Comment by liuyun1014** [comment]
Can provide mailbox, I send photos

**Comment by CaiJingLong** [comment]
email to me: cjl_spy@163.com

**Comment by liuyun1014** [comment]
Mail has been sent

**Comment by CaiJingLong** [comment]
Because my android 9.0 device does not use a similar error even if I don't use SampleSize, I need human support testing.

----
dependencies:
  flutter_image_compress: 
    git:
      url: https://github.com/OpenFlutter/flutter_image_compress.git
      ref: 2254a73ef9cfb2458d8cf54902c24d39cc263a49

**Comment by CaiJingLong** [comment]
If the test passes, I will push this change to the new version.

**Comment by liuyun1014** [comment]
Memory overflow error still exists, but does not flicker

**Comment by CaiJingLong** [comment]
I will confirm again, this situation generally appears in devices below 6.0 or 7.0?

Can you provide statistics for the android os version of the crash?

**Comment by liuyun1014** [comment]
I tested it with Android 6.0.1

**Comment by crazecoder** [comment]
https://stackoverflow.com/questions/19678665/bitmapfactory-decodefile-out-of-memory-with-images-2400x2400
@CaiJingLong  也许你可以试试这个

**Comment by CaiJingLong** [comment]
> https://stackoverflow.com/questions/19678665/bitmapfactory-decodefile-out-of-memory-with-images-2400x2400
> @CaiJingLong 也许你可以试试这个

The source look like #78 . But according to feedback, it seems to be invalid.

**Comment by crazecoder** [comment]
```
options.inJustDecodeBounds = false;
options.inPreferredConfig = Config.RGB_565;
options.inDither = true;
```
