### ISSUE TITLE
White line after compression

### ISSUE THREAD

**Issue by KasemJaffer** [OpenFlutter/flutter_image_compress#79]
Hi, thanks for the plugin. I have this issue on iOS where all the images after compression have a thin white line on the right and bottom edge of the image. 

**Input Description:**

**File**: Image file
**Mime Type**: heic
**Original Dimensions**: 4032 × 3024
**Required Image Dimensions**: 360 x 360

Thanks,
Kasem

**Comment by CaiJingLong** [comment]
Can you provider a picture?
You can send email to me or add it as an attachment to the comments.

By the way, cropping is not currently supported. Zooming only while maintaining the aspect ratio.

**Comment by KasemJaffer** [comment]
Hi,

Thank you for replying. Please find the original and compressed image file
attached.

Thanks,
Kasem

**Comment by KasemJaffer** [comment]
Just created a pull request containing a fix for this issue.

**Comment by CaiJingLong** [comment]
Thanks for PR.  I will review it as soon as possible.

**Comment by lifenautjoe** [comment]
Hi @CaiJingLong , have you had a chance to look into the PR? having the same issue on iOS
