### ISSUE TITLE
Compress to maximum dimension

### ISSUE THREAD

**Issue by ghost** [OpenFlutter/flutter_image_compress#84]
It would be interesting if there was an option to compress an image to a maximum dimension.  

Diving in some implementation details, given a maximum dimension of 1280 x 1280, this package would identify which side is larger (height or width), resize this side to 1280 and resize the other side keeping the original aspect ratio. It is important to know which side is larger because if you resize the smaller side to 1280 and resize the larger one to keep the aspect ratio, the latter size would be larger than 1280.

For example, an image 4000 x 3000 would become 1280 x 960.

**Comment by CaiJingLong** [comment]
dup of #82
