### ISSUE TITLE
Support WebP compressing

### ISSUE THREAD

**Issue by hugocbpassos** [OpenFlutter/flutter_image_compress#87]
It would be great to have WebP compressing.

With the same compressing configurations, I was able to get an image with half of the disk size of a JPG compress, when using this plugin (which looks like a fork of `flutter_image_compress` ): https://github.com/nucleartux/flutter_webp

**Comment by CaiJingLong** [comment]
Although the webp format has the native support of android, it is not difficult to add support in this part.
But for ios, you need to code and compress yourself. There is currently no way to support it. I have not found a suitable third-party library to support this work.

**Comment by hugocbpassos** [comment]
@CaiJingLong Perhaps a react native implementation can help you: https://github.com/TGPSKI/react-native-webp-support

**Comment by CaiJingLong** [comment]
Webp is supported.

**Comment by hugocbpassos** [comment]
@CaiJingLong I've seen you updated the docs with:

> Heif and webp Partially supported.

But also:

> And support iOS, but However, no system implementation, using third-party libraries used, it is not recommended due to encoding speed. In the future, libwebp by google (c / c ++) may be used to do coding work, bypassing other three-party libraries, but there is no guarantee of implementation time.

Why would you say WebP is partially supported? You added the feature in both Android and iOS. I feel like you actually meant that WebP is fully supported, but iOS's implementation needs improvements.

**Comment by CaiJingLong** [comment]
Maybe I forget the readme of webp format.

I will update it, thx for issue.

**Comment by Liloupar** [comment]
> Maybe I forget the readme of webp format.
> 
> I will update it, thx for issue.

这个好像还是没更新文档? 现在iOS实际上用的是libwebp吧?
