### ISSUE TITLE
transparent image turns black after compress in android

### ISSUE THREAD

**Issue by EzekR** [OpenFlutter/flutter_image_compress#89]
the plugin works fine when compressing an image with transparent background in iOS, however in android, the background changes to black after compress. How to solve this problem?

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_image_compress#format

**Comment by EzekR** [comment]
> https://github.com/OpenFlutter/flutter_image_compress#format

原来如此，多谢大大。
