### ISSUE TITLE
Support compressing from rawRGB

### ISSUE THREAD

**Issue by ianpark** [OpenFlutter/flutter_image_compress#91]
### Feature
Support compressing from rawRGB

### Detail
To capture the current widget, I use `RenderRepaintBoundary` like below.
```
RenderRepaintBoundary boundary =
      ImagePanel.globalKey.currentContext.findRenderObject();
  ui.Image image = await boundary.toImage(pixelRatio: 3);
  ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
  Uint8List result = byteData.buffer.asUint8List();
```
However ` image.toByteData()` is super slow if it is called with `ImageByteFormat.png` but super fast with `ImageByteFormat.rawRgb`.

If `flutter_image_compress` supports compressing from rawRGB, it's going to solve this problem.

**Comment by CaiJingLong** [comment]
Unable to process, raw is unprocessed raw data, similar to yuv data, which only contains color information, not even width and height.

**Comment by CaiJingLong** [comment]
I'll close it, because in my opinion this is not a problem.

**Comment by cmkweber** [comment]
I can confirm with my tests there would be a major speed improvement if rawRgb was used.

**Comment by rivereed** [comment]
+1 for the ability to pass in raw RGB[A} and produce an image. Easy to specify this (with whatever simplifications you want, like only support srgb and rgba byte order for now)
