### ISSUE TITLE
Grade minimum version error

### ISSUE THREAD

**Issue by lifenautjoe** [OpenFlutter/flutter_image_compress#92]
```

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lifenautjoe/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/android/build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'flutter_image_compress'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/lifenautjoe/.pub-cache/hosted/pub.dartlang.org/flutter_image_compress-0.6.3/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by CaiJingLong** [comment]
If the error message is the same, please update your gradle version.

**Comment by CaiJingLong** [comment]
I'll close it.
You just edit your gradle/wrapper/*.properties  Use the 5.1.1 version or higher. (Now the new latest version is 6.0.1)

**Comment by zzlhr** [comment]
> I'll close it.
> You just edit android/gradle/wrapper/*.properties in your project. Use the 5.1.1 version or higher. (Now the new latest version is 6.0.1)

need add classpath 'com.android.tools.build:gradle:3.1.1' to buildscript->dependencies

**Comment by CaiJingLong** [comment]
> > I'll close it.
> > You just edit android/gradle/wrapper/*.properties in your project. Use the 5.1.1 version or higher. (Now the new latest version is 6.0.1)
> 
> need add classpath 'com.android.tools.build:gradle:3.1.1' to buildscript->dependencies

Under normal circumstances, Android projects will add this by default. Without this, your module-level build.script cannot use plugin: android.

classpath generally corresponds to your android studio version number, you can use 3.4 3.5 3.6 according to your situation

**Comment by BadReese** [comment]
anyother solution? nothing work above..
