### ISSUE TITLE
how to delete the scaled_XXX.jpg file after compress?

### ISSUE THREAD

**Issue by xb284524239** [OpenFlutter/flutter_image_compress#93]
After i compress a image file like this: 

List<int> imgBytes = await FlutterImageCompress.compressWithFile("xxx.jpg");

the compress plugin will make a scaled file in the Pictures directory：

the scaled file's path like these: 

/storage/emulated/0/Android/data/com.ywj.fd.app.family_doctor_app_resident/files/Pictures/scaled_scaled_scaled_scaled_c57c469a-4afb-40a5-8062-af9ae78dabc64003503382529478024.jpg

/storage/emulated/0/Android/data/com.ywj.fd.app.family_doctor_app_resident/files/Pictures/scaled_scaled_c57c469a-4afb-40a5-8062-af9ae78dabc64003503382529478024.jpg

How to delete them?

**Comment by CaiJingLong** [comment]
This plugin does not create any cache files except the one you specify.

If this file is your image source file, then you can use `File(path).delete();` to delete file.

**Comment by VigneshPasupathy** [comment]
Are you using image_cropper plugin by any chance?
The File that you have mentioned gets created for all images that go through image_cropper in my application.
