### ISSUE TITLE
Compression type and input image type

### ISSUE THREAD

**Issue by EricPreventa** [OpenFlutter/flutter_image_compress#95]
Didn't see it mentioned what type of compression is used? I'm looking for a lossless compression. If I set quality = 100, would that still compress?

Also, what input image formats do you accept?

**Comment by CaiJingLong** [comment]
Param `format` is output format. If your image is png and have transparent information,  output format is jpeg, then the trans info will lost and fill with black.

Param `quality `is the quality when encoding the image.
It is 100 just does not compress the mass, but the size will still be scaled/rotated according to other parameters.
