### ISSUE TITLE
After compressing the picture, the next time you take a picture, you will get the picture that was compressed last time. How to solve it?

### ISSUE THREAD

**Issue by wuhuaqing** [OpenFlutter/flutter_image_compress#96]

**Comment by sagarzala123** [comment]
There is two ways to get rid from this,

1. After use of compressed picture, remove it if you don't want to use in future. 
2. Put compressed picture to hidden directory, so it can't be visible.

**Comment by CaiJingLong** [comment]
If the compression target is a file, the storage directory is up to you.

If it is stored in the MediaStore directory of an external SD card, it will be obtained by Photos or similar applications when an album scan event is triggered (such as restarting the device, taking a picture, etc.).

So I think you should listen to @sagarzala123,  delete them after upload.
