### ISSUE TITLE
Add support for HEIC/HEIF compression

### ISSUE THREAD

**Issue by Ainiuso** [OpenFlutter/flutter_image_compress#99]
HEIF potentially offers more efficient compression than JPEG while offering better image quality. It's supported since Android P and iOS 11.
Since Flutter doesn't yet have codecs for HEIF format, it could be a big benefit of this lib to provide at least option for compression.

**Comment by CaiJingLong** [comment]
0.6.4 will support heic format.
Specific support can be found in the readme.

**Comment by simanlx** [comment]
ios 我跑不来啊！

**Comment by homeserve-lsaudon** [comment]
Add support for web too
